### ISSUE TITLE
Приложение не запускается

### ISSUE THREAD

**Issue by gsbelarus** [GoldenSoftwareLtd/GedeminIncome#1]
Перекомпилировал из исходников из гита. Загрузил на маркет. Теперь, после обновления приложение не запускается. Сразу падает.

**Comment by gsbelarus** [comment]
java.lang.NoClassDefFoundError: Failed resolution of: Lcom/afollestad/materialdialogs/MaterialDialog$Builder;
at com.gsbelarus.gedemin.lib.ui.dialog.DatePickerDialog.<init>(DatePickerDialog.java:53)
at com.gsbelarus.gedemin.lib.ui.viewpager.ViewPagerDateModel.initDatePicker(ViewPagerDateModel.java:126)
at com.gsbelarus.gedemin.lib.ui.viewpager.ViewPagerDateModel.initView(ViewPagerDateModel.java:97)
at com.gsbelarus.gedemin.lib.ui.fragment.FragmentModel$1$1.run(FragmentModel.java:227)
at android.os.Handler.handleCallback(Handler.java:739)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:145)
at android.app.ActivityThread.main(ActivityThread.java:5832)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)
Caused by: java.lang.ClassNotFoundException: Didn't find class "com.afollestad.materialdialogs.MaterialDialog$Builder" on path: DexPathList[[zip file "/data/app/com.gsbelarus.gedemin.income-1/base.apk"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]
at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
... 12 more
Suppressed: java.lang.ClassNotFoundException: com.afollestad.materialdialogs.MaterialDialog$Builder
at java.lang.Class.classForName(Native Method)
at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
... 13 more
Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available
